<?php
/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

$sLangName = "English";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                                   => 'UTF-8',

    'SHOP_MODULE_GROUP_FCWLOP_GENERAL'                          => 'Basic configuration',
    'SHOP_MODULE_sFcwlopMode'                                   => 'Mode',
    'SHOP_MODULE_sFcwlopPspId'                                  => 'PspId',
    'SHOP_MODULE_sFcwlopMode_live'                              => 'Live',
    'SHOP_MODULE_sFcwlopMode_test'                              => 'Sandbox',
    'SHOP_MODULE_sFcwlopApiKey'                                 => 'API Key',
    'SHOP_MODULE_sFcwlopApiSecret'                              => 'API Secret',
    'SHOP_MODULE_sFcwlopWebhookKey'                             => 'Webhook key',
    'SHOP_MODULE_sFcwlopWebhookSecret'                          => 'Webhook secret',
    'SHOP_MODULE_sFcwlopLiveEndpoint'                           => 'Live endpoint',
    'SHOP_MODULE_sFcwlopSandboxEndpoint'                        => 'Sandbox endpoint',
    'SHOP_MODULE_sFcwlopFullRedirectTemplate'                   => 'Full Redirect template name',
    'SHOP_MODULE_sFcwlopIframeTemplate'                         => 'Iframe template name',

    'SHOP_MODULE_GROUP_FCWLOP_PAYMENT_METHODS'                  => 'Payment methods configuration',
    'SHOP_MODULE_sFcwlopCaptureMethod'                          => 'Capture mode',
    'SHOP_MODULE_sFcwlopCaptureMethod_direct-sales'             => 'Direct Sales',
    'SHOP_MODULE_sFcwlopCaptureMethod_manual'                   => 'Manual',
    'SHOP_MODULE_sFcwlopAutoCancellation'                       => 'Automatic cancellation',
    'SHOP_MODULE_sFcwlopAutoCancellation_0'                     => 'Inactive',
    'SHOP_MODULE_sFcwlopAutoCancellation_1'                     => 'In 1 hour',
    'SHOP_MODULE_sFcwlopAutoCancellation_2'                     => 'In 2 hours',
    'SHOP_MODULE_sFcwlopAutoCancellation_4'                     => 'In 4 hours',
    'SHOP_MODULE_sFcwlopAutoCancellation_6'                     => 'In 6 hours',
    'SHOP_MODULE_sFcwlopAutoCancellation_12'                    => 'In 12 hours',
    'SHOP_MODULE_sFcwlopAutoCancellation_24'                    => 'In 24 hours',
    'SHOP_MODULE_sFcwlopCcCheckoutType'                         => 'Credit card checkout type',
    'SHOP_MODULE_sFcwlopCcCheckoutType_embedded'                => 'On payment page',
    'SHOP_MODULE_sFcwlopCcCheckoutType_iframe'                  => 'Redirected',
    'SHOP_MODULE_sFcwlopCcGroupDisplay'                         => 'Group credit cards',

    'SHOP_MODULE_GROUP_FCWLOP_ERROR_MAPPING'                    => 'Error messages mapping',

    'FCWLOP_CONFIG_WEBHOOK_URL_LABEL'                           => 'Webhook exposed URL',
    'FCWLOP_CONFIG_WEBHOOK_URL_BUTTON'                          => 'Copy to clipboard',
    'FCWLOP_CONFIG_WEBHOOK_URL_COPIED'                          => 'URL Copied.',

    'FCWLOP_OPEN_ACCOUNT_DESCRIPTION'                           => 'You don\'t have Worldline account yet?',
    'FCWLOP_OPEN_ACCOUNT_BUTTON'                                => 'Open a Worldline account',
    'FCWLOP_CONFIG_TEST_CONNECTION'                             => 'Test connection',
    'FCWLOP_INSTALLATION_SUCCEEDED'                             => 'Methods successfully installed',
    'FCWLOP_INSTALLATION_FAILED'                                => 'Methods installation failed',
    'FCWLOP_CONNECTION_SUCCEEDED'                               => 'Successfully connected',
    'FCWLOP_CONNECTION_FAILED'                                  => 'Connection failed',
    
    'FCWLOP_CONFIG_UPDATE_PAYMENT_METHOD'                       => 'Payment methods setup / update',
    'FCWLOP_CONFIGURATION_UPDATE_SUCCESS'                       => 'Payment methods successfully updated.',
    'FCWLOP_CONFIGURATION_UPDATE_SUCCESS_WITH_MISSING'          => 'Payment methods updated, some new methods could not be added.',
    'FCWLOP_CONFIGURATION_UPDATE_ERROR'                         => 'Payment methods update failed.',

    'fcwlop_admin_protocol'                                     => 'Worldline Protocols / Logs',
    'fcwlop_admin_request_logs'                                 => 'API-Logs',
    'fcwlop_admin_transaction_logs'                             => 'Transactions-Logs',
    'fcwlop_order_title'                                        => 'Worldline',
    'FCWLOP_LIST_HEADER_TIMESTAMP'                              => 'DATE/TIME',
    'FCWLOP_LIST_HEADER_CHANNEL'                                => 'CHANNEL',
    'FCWLOP_LIST_HEADER_REQUEST'                                => 'REQUEST',
    'FCWLOP_LIST_HEADER_RESPONSE'                               => 'RESPONSE',
    'FCWLOP_LIST_HEADER_TXTIME'                                 => 'TXTIME',
    'FCWLOP_LIST_HEADER_ORDERNR'                                => 'ORDERNR',
    'FCWLOP_LIST_HEADER_TXID'                                   => 'TXID',
    'FCWLOP_LIST_HEADER_TYPE'                                   => 'TYPE',
    'FCWLOP_LIST_HEADER_PRICE'                                  => 'AMOUNT',
    'FCWLOP_LIST_HEADER_STATUS'                                 => 'STATUS',
    'FCWLOP_LIST_HEADER_STATUSCODE'                             => 'CODE',
    'FCWLOP_NO_REQUESTLOG'                                      => 'No logs',

    'FCWLOP_WEBHOOK_EVENT_UNEXPECTED'                           => 'Webhook call contained invalid data.',
    'FCWLOP_WEBHOOK_SIGNATURE_FAILED'                           => 'Webhook call signature validation failed.',

    'FCWLOP_IS_WORLDLINE'                                       => 'This is a Worldline payment type',
    'FCWLOP_IS_NOT_WORLDLINE_ORDER'                             => 'This is not a Worldline order',
    'FCWLOP_NO_WORLDLINE_PAYMENT'                               => 'This order was not paid with Worldline.',
    'FCWLOP_MODULE_VERSION_OUTDATED'                            => 'Caution! The current module version is',
    'FCWLOP_PAYMENT_DETAILS'                                    => 'Payment details',
    'FCWLOP_PAYMENT_TYPE'                                       => 'Payment type',
    'FCWLOP_TRANSACTION_STATUS'                                 => 'Worldline Transaction Status',
    'FCWLOP_TRANSACTION_ID'                                     => 'Worldline Transaction ID',
    'FCWLOP_EXTERNAL_TRANSACTION_ID'                            => 'External Transaction ID',
    'FCWLOP_ORDER_EXTRA_INFO'                                   => 'Additional information',
    'FCWLOP_NOTICE'                                             => 'Notice',
    'FCWLOP_SUBSEQUENT_ORDER_COMPLETION'                        => 'Subsequent order completion',
    'FCWLOP_ORDER_PAYMENT_URL'                                  => 'Link to payment completion',
    'FCWLOP_SEND_SECOND_CHANCE_MAIL'                            => 'Send Second Chance Email',
    'FCWLOP_SECOND_CHANCE_MAIL_ALREADY_SENT'                    => 'The email has already been sent.',
    'FCWLOP_ORDER_ALREADY_REFUNDED'                             => 'This order has been refunded completely already.',
    'FCWLOP_ORDER_NOT_REFUNDABLE'                               => 'This order is not refundable.',
    'FCWLOP_REFUND_REMAINING'                                   => 'Refund remaining sum',
    'FCWLOP_REFUND_SUBMIT'                                      => 'Execute refund',
    'FCWLOP_FULL_REFUND'                                        => 'Full refund',
    'FCWLOP_FULL_REFUND_TEXT'                                   => 'Execute full refund with the amount of',
    'FCWLOP_FULL_REFUND_NOT_AVAILABLE'                          => 'A full refund is not available for this order anymore, there were partial refunds already.',
    'FCWLOP_REFUND_DESCRIPTION'                                 => 'Refund notice',
    'FCWLOP_REFUND_DESCRIPTION_PLACEHOLDER'                     => 'optional - max 140 characters',
    'FCWLOP_REFUND_REASON'                                      => 'Refund reason (optional)',
    'FCWLOP_PLEASE_SELECT'                                      => '-- Please select --',
    'FCWLOP_REFUND_DUPLICATE'                                   => 'Duplicate',
    'FCWLOP_REFUND_CUSTOMER'                                    => 'Requested by customer',
    'FCWLOP_REFUND_FRAUD'                                       => 'Fraud',
    'FCWLOP_TRANSACTIONS_DETAILS'                               => 'Transactions details',
    'FCWLOP_CAPTURE_MODE'                                       => 'Capture mode',
    'FCWLOP_DIRECT_SALES'                                       => 'Direct Sales',
    'FCWLOP_MANUAL_CAPTURE'                                     => 'Manual capture',
    'FCWLOP_AUTHORIZED_AMOUNT'                                  => 'Authorized amount',
    'FCWLOP_PAID_AMOUNT'                                        => 'Paid on ',
    'FCWLOP_LEFT_PREAUTHORIZED_AMOUNT'                          => 'Remain to capture ',
    'FCWLOP_CAPTURED_AMOUNT'                                    => 'Captured amount',
    'FCWLOP_CAPTURED_AMOUNT_TOTAL'                              => 'Total',
    'FCWLOP_REFUNDED_AMOUNT'                                    => 'Refunded amount',
    'FCWLOP_REFUNDED_AMOUNT_TOTAL'                              => 'Total',
    'FCWLOP_BALANCE'                                            => 'balance',
    'FCWLOP_PREAUTHORIZED_AMOUNT'                               => 'Preauthorized amount',
    'FCWLOP_CAPTURE_AMOUNT_GREATER_NULL'                        => 'Captured amount has to be greater than 0',
    'FCWLOP_ARE_YOU_SURE'                                       => 'Are you sure that you want to perform this action?',
    'FCWLOP_NO_TRANSACTION_STATUS_RECEIVED'                     => 'No transaction status received.',
    'FCWLOP_NO_OPERATION_STATUS_RECEIVED'                       => 'No operation status received.',
    'FCWLOP_BTN_EXECUTE'                                        => 'Execute',
    'FCWLOP_BTN_CAPTURE'                                        => 'Capture',
    'FCWLOP_BTN_REFUND'                                         => 'Refund',
    'FCWLOP_BTN_CANCEL'                                         => 'Cancel',
    'FCWLOP_CAPTURE'                                            => 'Capture',
    'FCWLOP_CAPTURE_BY_ITEM'                                    => 'Capture by item',
    'FCWLOP_CAPTURE_BY_AMOUNT'                                  => 'Capture by amount',
    'FCWLOP_AMOUNT_IN'                                          => 'Amount in',
    'FCWLOP_PRODUCT_CAPTURE'                                    => 'Capture',
    'FCWLOP_PRODUCT_AMOUNT'                                     => 'Amount',
    'FCWLOP_PRODUCT_PRICE'                                      => 'Unit price',
    'FCWLOP_PRODUCT_TITLE'                                      => 'Product',
    'FCWLOP_SHIPPINGCOST'                                       => 'Shipping cost',
    'FCWLOP_PAYMENTTYPE'                                        => 'Payment type',
    'FCWLOP_WRAPPING'                                           => 'Gift Wrapping',
    'FCWLOP_GIFTCARD'                                           => 'Greeting Card',
    'FCWLOP_VOUCHER'                                            => 'Voucher',
    'FCWLOP_DISCOUNT'                                           => 'Discount',
    'FCWLOP_COMPLETE_ORDER'                                     => 'Complete order',
    'FCWLOP_CAPTURE_APPROVED'                                   => 'Capture was successful',
    'FCWLOP_CAPTURE_FAILED'                                     => 'Error occurred during booking: ',

    'FCWLOP_PRODUCT_REFUND'                                     => 'Refund',
    'FCWLOP_REFUND_BY_ITEM'                                     => 'Refund by item',
    'FCWLOP_REFUND_BY_AMOUNT'                                   => 'Refund by amount',
    'FCWLOP_REFUNDABLE_AMOUNT'                                  => 'Refundable amount',
    'FCWLOP_SURCHARGE'                                          => 'Surcharge',
    'FCWLOP_DEDUCTION'                                          => 'Deduction',
    'FCWLOP_REFUND_APPROVED'                                    => 'Refund was successful',
    'FCWLOP_REFUND_FAILED'                                      => 'Error occurred during refund: ',
    'FCWLOP_REFUND_AMOUNT_GREATER_NULL'                         => 'Refunded amount has to be greater than 0',

    'FCWLOP_CANCEL_ORDER'                                       => 'Order cancellation',
    'FCWLOP_CANCEL_ORDER_LABEL'                                 => 'Cancel the payment ? <br />(cannot be undone)',
    'FCWLOP_CANCEL_APPROVED'                                    => 'Order cancellation was successful',
    'FCWLOP_CANCEL_FAILED'                                      => 'Error occurred order cancellation: ',
);
