<?php
/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

$sLangName = "Deutsch";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                                   => 'UTF-8',

    'SHOP_MODULE_GROUP_FCWLOP_GENERAL'                          => 'Grundkonfiguration',
    'SHOP_MODULE_sFcwlopMode'                                   => 'Modus',
    'SHOP_MODULE_sFcwlopPspId'                                  => 'PspId',
    'SHOP_MODULE_sFcwlopMode_live'                              => 'Live',
    'SHOP_MODULE_sFcwlopMode_test'                              => 'Sandbox',
    'SHOP_MODULE_sFcwlopApiKey'                                 => 'API Key',
    'SHOP_MODULE_sFcwlopApiSecret'                              => 'API Secret',
    'SHOP_MODULE_sFcwlopWebhookKey'                             => 'Webhook key',
    'SHOP_MODULE_sFcwlopWebhookSecret'                          => 'Webhook secret',
    'SHOP_MODULE_sFcwlopLiveEndpoint'                           => 'Live endpoint',
    'SHOP_MODULE_sFcwlopSandboxEndpoint'                        => 'Sandbox endpoint',

    'SHOP_MODULE_GROUP_FCWLOP_PAYMENT_METHODS'                  => 'Zahlungsmethoden Konfiguration',
    'SHOP_MODULE_sFcwlopCaptureMethod'                          => 'Capture-Modus',
    'SHOP_MODULE_sFcwlopCaptureMethod_direct-sales'             => 'Direct Sales',
    'SHOP_MODULE_sFcwlopCaptureMethod_manual'                   => 'Manuell',
    'SHOP_MODULE_sFcwlopAutoCancellation'                       => 'Automatische Stornierung',
    'SHOP_MODULE_sFcwlopAutoCancellation_0'                     => 'Inaktiv',
    'SHOP_MODULE_sFcwlopAutoCancellation_1'                     => 'In 1 Stunde',
    'SHOP_MODULE_sFcwlopAutoCancellation_2'                     => 'In 2 Stunden',
    'SHOP_MODULE_sFcwlopAutoCancellation_4'                     => 'In 4 Stunden',
    'SHOP_MODULE_sFcwlopAutoCancellation_6'                     => 'In 6 Stunden',
    'SHOP_MODULE_sFcwlopAutoCancellation_12'                    => 'In 12 Stunden',
    'SHOP_MODULE_sFcwlopAutoCancellation_24'                    => 'In 24 Stunden',
    'SHOP_MODULE_sFcwlopCcCheckoutType'                         => 'Art der Kreditkartenzahlung',
    'SHOP_MODULE_sFcwlopCcCheckoutType_embedded'                => 'Auf der Zahlungsseite',
    'SHOP_MODULE_sFcwlopCcCheckoutType_iframe'                  => 'Umgeleitet',
    'SHOP_MODULE_sFcwlopCcGroupDisplay'                         => 'Kreditkarten gruppieren',

    'HELP_SHOP_MODULE_sFcwlopMode'                              => 'Sandbox = Testmodus, Live = Produktion.',
    'HELP_SHOP_MODULE_sFcwlopPspId'                             => 'Worldline-Konto-ID.',
    'HELP_SHOP_MODULE_sFcwlopApiKey'                            => 'Gefunden auf dem Worldine API-Portal.',
    'HELP_SHOP_MODULE_sFcwlopApiSecret'                         => 'Gefunden auf dem Worldine API-Portal.',
    'HELP_SHOP_MODULE_sFcwlopWebhookKey'                        => 'Gefunden auf dem Worldine API-Portal.',
    'HELP_SHOP_MODULE_sFcwlopWebhookSecret'                     => 'Gefunden auf dem Worldine API-Portal.',
    'HELP_SHOP_MODULE_sFcwlopLiveEndpoint'                      => 'https://payment.direct.worldline-solutions.com ohne abschließendes / oder irgendeinen Zusatz.',
    'HELP_SHOP_MODULE_sFcwlopSandboxEndpoint'                   => 'https://payment.preprod.direct.worldline-solutions.com ohne abschließendes / oder irgendeinen Zusatz.',
    'HELP_SHOP_MODULE_sFcwlopCaptureMethod'                     => 'Capture-Modus : Direct Sales = Autorisierung + Erfassung, Manuell = separate Erfassung manuell.',
    'HELP_SHOP_MODULE_sFcwlopCcCheckoutType'                    => 'Auf der Zahlungsseite = Kartendatenerfassung im Shop ohne Weiterleitung, Umgeleitet = Kartendatenerfassung durch Worldline auf ihrer Seite.',
    'HELP_SHOP_MODULE_sFcwlopCcGroupDisplay'                    => 'Kreditkartenauswahl auf der gehosteten Checkout-Seite nach der Weiterleitung anzeigen.',

    'FCWLOP_CONFIG_WEBHOOK_URL_LABEL'                           => 'Webhook URL',
    'FCWLOP_CONFIG_WEBHOOK_URL_BUTTON'                          => 'In die Zwischenablage kopieren',
    'FCWLOP_CONFIG_WEBHOOK_URL_COPIED'                          => 'URL kopiert.',

    'FCWLOP_OPEN_ACCOUNT_DESCRIPTION'                           => 'Sie haben noch kein Worldline-Konto?',
    'FCWLOP_OPEN_ACCOUNT_BUTTON'                                => 'Worldline-Konto öffnen',
    'FCWLOP_CONFIG_TEST_CONNECTION'                             => 'Verbindungstest',
    'FCWLOP_INSTALLATION_SUCCEEDED'                             => 'Zahlungsmethoden erfolgreich installiert',
    'FCWLOP_INSTALLATION_FAILED'                                => 'Installation der Zahlungsmethoden fehlgeschlagen',
    'FCWLOP_CONNECTION_SUCCEEDED'                               => 'Verbindung erfolgreich',
    'FCWLOP_CONNECTION_FAILED'                                  => 'Verbindung nicht erfolgreich',
    
    'FCWLOP_CONFIG_UPDATE_PAYMENT_METHOD'                       => 'Zahlungsmethoden einrichten / aktualisieren',
    'FCWLOP_CONFIGURATION_UPDATE_SUCCESS'                       => 'Zahlungsmethoden erfolgreich aktualisiert.',
    'FCWLOP_CONFIGURATION_UPDATE_SUCCESS_WITH_MISSING'          => 'Zahlungsmethoden aktualisiert, einige neue Methoden konnten nicht hinzugefügt werden.',
    'FCWLOP_CONFIGURATION_UPDATE_ERROR'                         => 'Die Aktualisierung der Zahlungsmethoden ist fehlgeschlagen.',

    'fcwlop_admin_protocol'                                     => 'Worldline Protokolle / Logs',
    'fcwlop_admin_request_logs'                                 => 'API-Logs',
    'fcwlop_admin_transaction_logs'                             => 'Transaktionsprotokolle',
    'fcwlop_order_title'                                        => 'Worldline',
    'FCWLOP_LIST_HEADER_TIMESTAMP'                              => 'DATUM/UHRZEIT',
    'FCWLOP_LIST_HEADER_CHANNEL'                                => 'KANAL',
    'FCWLOP_LIST_HEADER_REQUEST'                                => 'REQUEST',
    'FCWLOP_LIST_HEADER_RESPONSE'                               => 'RESPONSE',
    'FCWLOP_LIST_HEADER_TXTIME'                                 => 'TXTIME',
    'FCWLOP_LIST_HEADER_ORDERNR'                                => 'BESTELLNR.',
    'FCWLOP_LIST_HEADER_TXID'                                   => 'TXID',
    'FCWLOP_LIST_HEADER_TYPE'                                   => 'TYP',
    'FCWLOP_LIST_HEADER_PRICE'                                  => 'BETRAG',
    'FCWLOP_LIST_HEADER_STATUS'                                 => 'STATUS',
    'FCWLOP_LIST_HEADER_STATUSCODE'                             => 'CODE',
    'FCWLOP_NO_REQUESTLOG'                                      => 'Keine Log',

    'FCWLOP_WEBHOOK_EVENT_UNEXPECTED'                           => 'Der Webhook-Aufruf enthielt ungültige Daten.',
    'FCWLOP_WEBHOOK_SIGNATURE_FAILED'                           => 'Die Validierung der Webhook-Anrufsignatur ist fehlgeschlagen.',

    'FCWLOP_IS_WORLDLINE'                                       => 'Dies ist eine Worldline Zahlungsart',
    'FCWLOP_IS_NOT_WORLDLINE_ORDER'                             => 'Dies ist keine Worldline Bestellung',
    'FCWLOP_NO_WORLDLINE_PAYMENT'                               => 'Diese Bestellung wurde nicht mit Worldline bezahlt.',
    'FCWLOP_MODULE_VERSION_OUTDATED'                            => 'Achtung! Die aktuellste Modulversion ist',
    'FCWLOP_PAYMENT_DETAILS'                                    => 'Zahlungsdetails',
    'FCWLOP_PAYMENT_TYPE'                                       => 'Zahlarten',
    'FCWLOP_TRANSACTION_STATUS'                                 => 'Worldline Transaktion Status',
    'FCWLOP_TRANSACTION_ID'                                     => 'Worldline Transaktion ID',
    'FCWLOP_EXTERNAL_TRANSACTION_ID'                            => 'Externe Transaktion ID',
    'FCWLOP_ORDER_EXTRA_INFO'                                   => 'Zus&auml;tzliche information',
    'FCWLOP_NOTICE'                                             => 'Hinweis',
    'FCWLOP_SUBSEQUENT_ORDER_COMPLETION'                        => 'Nachtr&auml;glicher Bestellabschluss',
    'FCWLOP_ORDER_PAYMENT_URL'                                  => 'Link zum Abschluss der Zahlung',
    'FCWLOP_SEND_SECOND_CHANCE_MAIL'                            => 'Second Chance Email versenden',
    'FCWLOP_SECOND_CHANCE_MAIL_ALREADY_SENT'                    => 'Die Email wurde bereits versendet.',
    'FCWLOP_ORDER_ALREADY_REFUNDED'                             => 'Diese Bestellung wurde bereits vollst&auml;ndig erstattet.',
    'FCWLOP_ORDER_NOT_REFUNDABLE'                               => 'Diese Bestellung ist nicht erstattungsf&auml;hig.',
    'FCWLOP_REFUND_REMAINING'                                   => 'Verbliebene Summe erstatten',
    'FCWLOP_REFUND_SUBMIT'                                      => 'Erstattung durchf&uuml;hren',
    'FCWLOP_FULL_REFUND'                                        => 'Vollst&auml;ndige R&uuml;ckerstattung',
    'FCWLOP_FULL_REFUND_TEXT'                                   => 'Vollst&auml;ndige Erstattung durchf&uuml;hren &uuml;ber Betrag von',
    'FCWLOP_FULL_REFUND_NOT_AVAILABLE'                          => 'Eine Vollst&auml;ndige R&uuml;ckerstattung ist f&uuml;r diese Bestellung nicht mehr verf&uuml;gbar, da Sie bereits Einzelpositionen zur&uuml;ckerstattet haben.',
    'FCWLOP_REFUND_DESCRIPTION'                                 => 'Erstattungs-Hinweis',
    'FCWLOP_REFUND_DESCRIPTION_PLACEHOLDER'                     => 'Optional - Max 140 Zeichen',
    'FCWLOP_REFUND_REASON'                                      => 'R&uuml;ckerstattungsgrund (optional)',
    'FCWLOP_PLEASE_SELECT'                                      => '-- Bitte w&auml;hlen Sie --',
    'FCWLOP_REFUND_DUPLICATE'                                   => 'Duplikat',
    'FCWLOP_REFUND_CUSTOMER'                                    => 'Vom Kunden angefordert',
    'FCWLOP_REFUND_FRAUD'                                       => 'Betrug',
    'FCWLOP_TRANSACTIONS_DETAILS'                               => 'Transaktionsdetails',
    'FCWLOP_CAPTURE_MODE'                                       => 'Erfassungsmodus',
    'FCWLOP_DIRECT_SALES'                                       => 'Direct Sales',
    'FCWLOP_MANUAL_CAPTURE'                                     => 'Manuelle Erfassung',
    'FCWLOP_AUTHORIZED_AMOUNT'                                  => 'Autorisierter Betrag',
    'FCWLOP_PAID_AMOUNT'                                        => 'Bezahlt am ',
    'FCWLOP_LEFT_PREAUTHORIZED_AMOUNT'                          => 'Rest zu erfassen ',
    'FCWLOP_CAPTURED_AMOUNT'                                    => 'Erfasster Betrag',
    'FCWLOP_CAPTURED_AMOUNT_TOTAL'                              => 'Gesamt',
    'FCWLOP_REFUNDED_AMOUNT'                                    => 'Rückerstatteter Betrag',
    'FCWLOP_REFUNDED_AMOUNT_TOTAL'                              => 'Gesamt',
    'FCWLOP_BALANCE'                                            => 'Saldo',
    'FCWLOP_PREAUTHORIZED_AMOUNT'                               => 'Vorautorisierter Betrag',
    'FCWLOP_CAPTURE_AMOUNT_GREATER_NULL'                        => 'Erfasster Betrag muss größer als 0 sein',
    'FCWLOP_ARE_YOU_SURE'                                       => 'Sind Sie sicher, dass Sie diese Aktion ausführen möchten?',
    'FCWLOP_NO_TRANSACTION_STATUS_RECEIVED'                     => 'Kein Transaktionsstatus empfangen.',
    'FCWLOP_NO_OPERATION_STATUS_RECEIVED'                       => 'Kein Vorgangsstatus empfangen.',
    'FCWLOP_BTN_EXECUTE'                                        => 'Ausführen',
    'FCWLOP_BTN_CAPTURE'                                        => 'Erfassen',
    'FCWLOP_BTN_REFUND'                                         => 'Rückerstattung',
    'FCWLOP_BTN_CANCEL'                                         => 'Stornieren',
    'FCWLOP_CAPTURE'                                            => 'Erfassung',
    'FCWLOP_CAPTURE_BY_ITEM'                                    => 'Erfassung nach Artikel',
    'FCWLOP_CAPTURE_BY_AMOUNT'                                  => 'Erfassung nach Betrag',
    'FCWLOP_AMOUNT_IN'                                          => 'Betrag in',
    'FCWLOP_PRODUCT_CAPTURE'                                    => 'Erfassen',
    'FCWLOP_PRODUCT_AMOUNT'                                     => 'Betrag',
    'FCWLOP_PRODUCT_PRICE'                                      => 'Stückpreis',
    'FCWLOP_PRODUCT_TITLE'                                      => 'Produkt',
    'FCWLOP_SHIPPINGCOST'                                       => 'Versandkosten',
    'FCWLOP_PAYMENTTYPE'                                        => 'Zahlungsart',
    'FCWLOP_WRAPPING'                                           => 'Geschenkverpackung',
    'FCWLOP_GIFTCARD'                                           => 'Gruß Karte',
    'FCWLOP_VOUCHER'                                            => 'Gutschein',
    'FCWLOP_DISCOUNT'                                           => 'Rabatt',
    'FCWLOP_COMPLETE_ORDER'                                     => 'Bestellung abschließen',
    'FCWLOP_CAPTURE_APPROVED'                                   => 'Erfassung war erfolgreich',
    'FCWLOP_CAPTURE_FAILED'                                     => 'Bei der Erfassung ist ein Fehler aufgetreten: ',

    'FCWLOP_PRODUCT_REFUND'                                     => 'Rückerstattung',
    'FCWLOP_REFUND_BY_ITEM'                                     => 'Rückerstattung nach Artikel',
    'FCWLOP_REFUND_BY_AMOUNT'                                   => 'Rückerstattung nach Betrag',
    'FCWLOP_REFUNDABLE_AMOUNT'                                  => 'Rückerstattungsfähiger Betrag',
    'FCWLOP_SURCHARGE'                                          => 'Aufpreis',
    'FCWLOP_DEDUCTION'                                          => 'Abzug',
    'FCWLOP_REFUND_APPROVED'                                    => 'Rückerstattung war erfolgreich',
    'FCWLOP_REFUND_FAILED'                                      => 'Bei der Rückerstattung ist ein Fehler aufgetreten: ',
    'FCWLOP_REFUND_AMOUNT_GREATER_NULL'                         => 'Rückerstattungsbetrag muss größer als 0 sein',
    'FCWLOP_REFUND_AMOUNT_LOWER_MAX'                            => 'Rückerstattungsbetrag darf nicht größer als Rückerstattungsfähiger Betrag sein',

    'FCWLOP_CANCEL_ORDER'                                       => 'Zahlungsstornierung',
    'FCWLOP_CANCEL_ORDER_LABEL'                                 => 'Zahlung stornieren? <br />(kann nicht rückgängig gemacht werden)',
    'FCWLOP_CANCEL_APPROVED'                                    => 'Zahlungsstornierung war erfolgreich',
    'FCWLOP_CANCEL_FAILED'                                      => 'Bei der Zahlungsstornierung ist ein Fehler aufgetreten: ',
);
